### ISSUE TITLE
There is no npm package with such name

### ISSUE THREAD

**Issue by budarin** [jhusain/eslint-plugin-immutable#3] opened 2016-03-11 15:34 UTC
try to install module but catch the error

**Comment by dapi** [comment] 2016-03-12 05:41
+1

**Comment by despairblue** [comment] 2016-03-14 13:59
duplicate of #1 

Use `npm install git://github.com/jhusain/eslint-plugin-immutable.git --save-dev` meanwhile.

**Closed as completed** 2017-11-24 20:47 UTC
